[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 20000


[fmt]
tab_width = 2

[fuzz]
runs=10000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
